print("Are you OK?")
test1=input()
print("No,I didn't talk to you ")
print("=========================")
print("介绍一下，这是我...")
test2=input()
print("才不是")
print("=========================")
print("test input")
print("=========================")
print(test1)
print(test2)
